=== Minisiia/XslTransformer/src/main/resources/5_computers/computers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Devices" type="DevicesType"/>
  <xs:complexType name="TypeType">
    <xs:sequence>
      <xs:element name="TypeComponent">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Peripheral"/>
            <xs:enumeration value="Non-Peripheral"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PowerConsumption">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="65"/>
            <xs:enumeration value="150"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Cooler">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Yes"/>
            <xs:enumeration value="No"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Group">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Input/Output Devices"/>
            <xs:enumeration value="Multimedia"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Ports">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="USB"/>
            <xs:enumeration value="USB, LPT"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ComponentType">
    <xs:sequence>
      <xs:element name="Name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Processor"/>
            <xs:enumeration value="Graphics Card"/>
            <xs:enumeration value="Memory"/>
            <xs:enumeration value="Hard Drive"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="USA"/>
            <xs:enumeration value="Taiwan"/>
            <xs:enumeration value="China"/>
            <xs:enumeration value="Japan"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Price">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1000"/>
            <xs:enumeration value="500"/>
            <xs:enumeration value="200"/>
            <xs:enumeration value="150"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="TypeType" name="Type"/>
      <xs:element name="Critical">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="No"/>
            <xs:enumeration value="Yes"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DevicesType">
    <xs:sequence>
      <xs:element type="ComponentType" name="Component" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Minisiia/XslTransformer/src/main/resources/5_computers/computers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="computers.xsd">
    <Component>
        <Name>Processor</Name>
        <Origin>USA</Origin>
        <Price>1000</Price>
        <Type>
            <TypeComponent>Peripheral</TypeComponent>
            <PowerConsumption>65</PowerConsumption>
            <Cooler>Yes</Cooler>
            <Group>Input/Output Devices</Group>
            <Ports>USB</Ports>
        </Type>
        <Critical>No</Critical>
    </Component>
    <Component>
        <Name>Graphics Card</Name>
        <Origin>Taiwan</Origin>
        <Price>500</Price>
        <Type>
            <TypeComponent>Peripheral</TypeComponent>
            <PowerConsumption>150</PowerConsumption>
            <Cooler>Yes</Cooler>
            <Group>Multimedia</Group>
            <Ports>USB</Ports>
        </Type>
        <Critical>Yes</Critical>
    </Component>
    <Component>
        <Name>Memory</Name>
        <Origin>China</Origin>
        <Price>200</Price>
        <Type>
            <TypeComponent>Non-Peripheral</TypeComponent>
            <PowerConsumption>5</PowerConsumption>
            <Cooler>No</Cooler>
            <Group>Input/Output Devices</Group>
            <Ports>USB</Ports>
        </Type>
        <Critical>No</Critical>
    </Component>
    <Component>
        <Name>Hard Drive</Name>
        <Origin>Japan</Origin>
        <Price>150</Price>
        <Type>
            <TypeComponent>Non-Peripheral</TypeComponent>
            <PowerConsumption>10</PowerConsumption>
            <Cooler>No</Cooler>
            <Group>Multimedia</Group>
            <Ports>USB, LPT</Ports>
        </Type>
        <Critical>Yes</Critical>
    </Component>
</Devices>
