=== Minisiia/XslTransformer/src/main/resources/4_medications/medications.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Medicine" type="MedicineType"/>
  <xs:complexType name="AnalogsType">
    <xs:sequence>
      <xs:element name="Analog" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Ibuprofen"/>
            <xs:enumeration value="Aspirin"/>
            <xs:enumeration value="Penicillin"/>
            <xs:enumeration value="Cephalexin"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CertificateType">
    <xs:sequence>
      <xs:element name="Number">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="12345"/>
            <xs:enumeration value="67890"/>
            <xs:enumeration value="67390"/>
            <xs:enumeration value="54321"/>
            <xs:enumeration value="09876"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IssueDate">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2022-01-01"/>
            <xs:enumeration value="2022-03-15"/>
            <xs:enumeration value="2020-03-15"/>
            <xs:enumeration value="2022-02-01"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ExpiryDate">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2023-12-31"/>
            <xs:enumeration value="2024-02-28"/>
            <xs:enumeration value="2020-02-18"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IssuingAuthority">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Drug Administration"/>
            <xs:enumeration value="Health Department"/>
            <xs:enumeration value="Н.K. Department"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PackageType">
    <xs:sequence>
      <xs:element name="Type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Blister Pack"/>
            <xs:enumeration value="Bottle"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Quantity">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="20"/>
            <xs:enumeration value="100"/>
            <xs:enumeration value="200"/>
            <xs:enumeration value="30"/>
            <xs:enumeration value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Price">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="5.99"/>
            <xs:enumeration value="12.99"/>
            <xs:enumeration value="20.99"/>
            <xs:enumeration value="9.99"/>
            <xs:enumeration value="4.99"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProducerType">
    <xs:sequence>
      <xs:element type="CertificateType" name="Certificate"/>
      <xs:element type="PackageType" name="Package"/>
      <xs:element name="Dosage">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="500mg"/>
            <xs:enumeration value="250mg"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Frequency">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Every 4-6 hours"/>
            <xs:enumeration value="Every 6-8 hours"/>
            <xs:enumeration value="Every 12 hours"/>
            <xs:enumeration value="Twice a day"/>
            <xs:enumeration value="Thrice a day"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProducersType">
    <xs:sequence>
      <xs:element type="ProducerType" name="Producer" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="VersionType">
    <xs:sequence>
      <xs:element name="Consistency">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Tablets"/>
            <xs:enumeration value="Syrup"/>
            <xs:enumeration value="Capsules"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="ProducersType" name="Producers"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="VersionsType">
    <xs:sequence>
      <xs:element type="VersionType" name="Version" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MedicationType">
    <xs:sequence>
      <xs:element name="Name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Paracetamol"/>
            <xs:enumeration value="Amoxicillin"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Group">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Analgesics"/>
            <xs:enumeration value="Antibiotics"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="AnalogsType" name="Analogs"/>
      <xs:element type="VersionsType" name="Versions"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MedicineType">
    <xs:sequence>
      <xs:element type="MedicationType" name="Medication" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Minisiia/XslTransformer/src/main/resources/4_medications/medications.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Medicine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="medications.xsd">
    <Medication>
        <Name>Paracetamol</Name>
        <Group>Analgesics</Group>
        <Analogs>
            <Analog>Ibuprofen</Analog>
            <Analog>Aspirin</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Consistency>Tablets</Consistency>
                <Producers>
                    <Producer>
                        <Certificate>
                            <Number>12345</Number>
                            <IssueDate>2022-01-01</IssueDate>
                            <ExpiryDate>2023-12-31</ExpiryDate>
                            <IssuingAuthority>Drug Administration</IssuingAuthority>
                        </Certificate>
                        <Package>
                            <Type>Blister Pack</Type>
                            <Quantity>20</Quantity>
                            <Price>5.99</Price>
                        </Package>
                        <Dosage>500mg</Dosage>
                        <Frequency>Every 4-6 hours</Frequency>
                    </Producer>
                    <Producer>
                        <Certificate>
                            <Number>67890</Number>
                            <IssueDate>2022-03-15</IssueDate>
                            <ExpiryDate>2024-02-28</ExpiryDate>
                            <IssuingAuthority>Health Department</IssuingAuthority>
                        </Certificate>
                        <Package>
                            <Type>Bottle</Type>
                            <Quantity>100</Quantity>
                            <Price>12.99</Price>
                        </Package>
                        <Dosage>250mg</Dosage>
                        <Frequency>Every 6-8 hours</Frequency>
                    </Producer>
                </Producers>
            </Version>
            <Version>
                <Consistency>Syrup</Consistency>
                <Producers>
                    <Producer>
                        <Certificate>
                            <Number>67390</Number>
                            <IssueDate>2020-03-15</IssueDate>
                            <ExpiryDate>2020-02-18</ExpiryDate>
                            <IssuingAuthority>–ù.K. Department</IssuingAuthority>
                        </Certificate>
                        <Package>
                            <Type>Bottle</Type>
                            <Quantity>200</Quantity>
                            <Price>20.99</Price>
                        </Package>
                        <Dosage>500mg</Dosage>
                        <Frequency>Every 12 hours</Frequency>
                    </Producer>
                </Producers>
            </Version>
        </Versions>
    </Medication>
    <Medication>
        <Name>Amoxicillin</Name>
        <Group>Antibiotics</Group>
        <Analogs>
            <Analog>Penicillin</Analog>
            <Analog>Cephalexin</Analog>
        </Analogs>
        <Versions>
            <Version>
                <Consistency>Capsules</Consistency>
                <Producers>
                    <Producer>
                        <Certificate>
                            <Number>54321</Number>
                            <IssueDate>2022-02-01</IssueDate>
                            <ExpiryDate>2023-12-31</ExpiryDate>
                            <IssuingAuthority>Drug Administration</IssuingAuthority>
                        </Certificate>
                        <Package>
                            <Type>Bottle</Type>
                            <Quantity>30</Quantity>
                            <Price>9.99</Price>
                        </Package>
                        <Dosage>500mg</Dosage>
                        <Frequency>Twice a day</Frequency>
                    </Producer>
                    <Producer>
                        <Certificate>
                            <Number>09876</Number>
                            <IssueDate>2022-03-15</IssueDate>
                            <ExpiryDate>2024-02-28</ExpiryDate>
                            <IssuingAuthority>Health Department</IssuingAuthority>
                        </Certificate>
                        <Package>
                            <Type>Blister Pack</Type>
                            <Quantity>10</Quantity>
                            <Price>4.99</Price>
                        </Package>
                        <Dosage>250mg</Dosage>
                        <Frequency>Thrice a day</Frequency>
                    </Producer>
                </Producers>
            </Version>
        </Versions>
    </Medication>
</Medicine>
