=== Minisiia/XslTransformer/src/main/resources/3_tariffs/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Tariff" type="TariffType"/>
  <xs:complexType name="CallPricesType">
    <xs:sequence>
      <xs:element name="InNetwork">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0.10"/>
            <xs:enumeration value="0.08"/>
            <xs:enumeration value="0.12"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="OutNetwork">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0.25"/>
            <xs:enumeration value="0.30"/>
            <xs:enumeration value="0.35"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Landline">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0.15"/>
            <xs:enumeration value="0.20"/>
            <xs:enumeration value="0.25"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParametersType">
    <xs:sequence>
      <xs:element name="FavoriteNumber">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="5"/>
            <xs:enumeration value="Unlimited"/>
            <xs:enumeration value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Billing">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Per-minute"/>
            <xs:enumeration value="Per-second"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ConnectionFee">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0"/>
            <xs:enumeration value="10"/>
            <xs:enumeration value="5"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RateType">
    <xs:sequence>
      <xs:element name="Name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Plan A"/>
            <xs:enumeration value="Plan B"/>
            <xs:enumeration value="Plan C"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="OperatorName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Mobile Operator A"/>
            <xs:enumeration value="Mobile Operator B"/>
            <xs:enumeration value="Mobile Operator C"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Payroll">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="25"/>
            <xs:enumeration value="50"/>
            <xs:enumeration value="30"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="CallPricesType" name="CallPrices"/>
      <xs:element name="SMSPrice">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0.05"/>
            <xs:enumeration value="0.03"/>
            <xs:enumeration value="0.08"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="ParametersType" name="Parameters"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TariffType">
    <xs:sequence>
      <xs:element type="RateType" name="Rate" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Minisiia/XslTransformer/src/main/resources/3_tariffs/tariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Tariff xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "tariffs.xsd">
    <Rate>
        <Name>Plan A</Name>
        <OperatorName>Mobile Operator A</OperatorName>
        <Payroll>25</Payroll>
        <CallPrices>
            <InNetwork>0.10</InNetwork>
            <OutNetwork>0.25</OutNetwork>
            <Landline>0.15</Landline>
        </CallPrices>
        <SMSPrice>0.05</SMSPrice>
        <Parameters>
            <FavoriteNumber>5</FavoriteNumber>
            <Billing>Per-minute</Billing>
            <ConnectionFee>0</ConnectionFee>
        </Parameters>
    </Rate>

    <Rate>
        <Name>Plan B</Name>
        <OperatorName>Mobile Operator B</OperatorName>
        <Payroll>50</Payroll>
        <CallPrices>
            <InNetwork>0.08</InNetwork>
            <OutNetwork>0.30</OutNetwork>
            <Landline>0.20</Landline>
        </CallPrices>
        <SMSPrice>0.03</SMSPrice>
        <Parameters>
            <FavoriteNumber>Unlimited</FavoriteNumber>
            <Billing>Per-minute</Billing>
            <ConnectionFee>10</ConnectionFee>
        </Parameters>
    </Rate>

    <Rate>
        <Name>Plan C</Name>
        <OperatorName>Mobile Operator C</OperatorName>
        <Payroll>30</Payroll>
        <CallPrices>
            <InNetwork>0.12</InNetwork>
            <OutNetwork>0.35</OutNetwork>
            <Landline>0.25</Landline>
        </CallPrices>
        <SMSPrice>0.08</SMSPrice>
        <Parameters>
            <FavoriteNumber>2</FavoriteNumber>
            <Billing>Per-second</Billing>
            <ConnectionFee>5</ConnectionFee>
        </Parameters>
    </Rate>
</Tariff>
