=== Minisiia/XslTransformer/src/main/resources/2_diamond_fund/diamond.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Gem" type="GemType"/>
  <xs:complexType name="VisualParametersType">
    <xs:sequence>
      <xs:element name="Color">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="White"/>
            <xs:enumeration value="Green"/>
            <xs:enumeration value="Purple"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Transparency">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="80"/>
            <xs:enumeration value="90"/>
            <xs:enumeration value="70"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Facets">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="57"/>
            <xs:enumeration value="15"/>
            <xs:enumeration value="12"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StoneType">
    <xs:sequence>
      <xs:element name="Name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Diamond"/>
            <xs:enumeration value="Emerald"/>
            <xs:enumeration value="Amethyst"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Preciousness">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Precious"/>
            <xs:enumeration value="Semi-precious"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="South Africa"/>
            <xs:enumeration value="Colombia"/>
            <xs:enumeration value="Brazil"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="VisualParametersType" name="VisualParameters"/>
      <xs:element name="Value">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1.5"/>
            <xs:enumeration value="0.75"/>
            <xs:enumeration value="0.4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GemType" mixed="true">
    <xs:sequence>
      <xs:element type="StoneType" name="Stone" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Minisiia/XslTransformer/src/main/resources/2_diamond_fund/diamond.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Gem xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation = "diamond.xsd">
        <Stone>
            <Name>Diamond</Name>
            <Preciousness>Precious</Preciousness>
            <Origin>South Africa</Origin>
            <VisualParameters>
                <Color>White</Color>
                <Transparency>80</Transparency>
                <Facets>57</Facets>
            </VisualParameters>
            <Value>1.5</Value>
        </Stone>
        <Stone>
            <Name>Emerald</Name>
            <Preciousness>Precious</Preciousness>
            <Origin>Colombia</Origin>
            <VisualParameters>
                <Color>Green</Color>
                <Transparency>90</Transparency>
                <Facets>15</Facets>
            </VisualParameters>
            <Value>0.75</Value>
        </Stone>
        <Stone>
            <Name>Amethyst</Name>
            <Preciousness>Semi-precious</Preciousness>
            <Origin>Brazil</Origin>
            <VisualParameters>
                <Color>Purple</Color>
                <Transparency>70</Transparency>
                <Facets>12</Facets>
            </VisualParameters>
            <Value>0.4</Value>
        </Stone>
    </Gem>
