=== Minisiia/XslTransformer/src/main/resources/7_cutlery/cutlery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FlatWare" type="FlatWareType"/>
  <xs:complexType name="TopPartType">
    <xs:sequence>
      <xs:element name="Length">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="150"/>
            <xs:enumeration value="40"/>
            <xs:enumeration value="30"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Width">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="20"/>
            <xs:enumeration value="5"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Material">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Steel"/>
            <xs:enumeration value="Copper"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MaterialType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="HandleType">
    <xs:sequence>
      <xs:element type="MaterialType" name="Material"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="VisualType">
    <xs:sequence>
      <xs:element type="TopPartType" name="TopPart"/>
      <xs:element type="HandleType" name="Handle"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CutleryType">
    <xs:sequence>
      <xs:element name="Type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Knife"/>
            <xs:enumeration value="Fork"/>
            <xs:enumeration value="Spoon"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Ukraine"/>
            <xs:enumeration value="China"/>
            <xs:enumeration value="Turkey"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="VisualType" name="Visual"/>
      <xs:element name="Value">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Non-collectible"/>
            <xs:enumeration value="Collectible"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FlatWareType">
    <xs:sequence>
      <xs:element type="CutleryType" name="Cutlery" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Minisiia/XslTransformer/src/main/resources/7_cutlery/cutlery.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FlatWare xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="cutlery.xsd">
    <Cutlery>
        <Type>Knife</Type>
        <Origin>Ukraine</Origin>
        <Visual>
            <TopPart>
                <Length>150</Length>
                <Width>20</Width>
                <Material>Steel</Material>
            </TopPart>
            <Handle>
                <Material type="Oak">Wood</Material>
            </Handle>
        </Visual>
        <Value>Non-collectible</Value>
    </Cutlery>
    <Cutlery>
        <Type>Fork</Type>
        <Origin>China</Origin>
        <Visual>
            <TopPart>
                <Length>40</Length>
                <Width>5</Width>
                <Material>Steel</Material>
            </TopPart>
            <Handle>
                <Material>Plastic</Material>
            </Handle>
        </Visual>
        <Value>Collectible</Value>
    </Cutlery>
    <Cutlery>
        <Type>Spoon</Type>
        <Origin>Turkey</Origin>
        <Visual>
            <TopPart>
                <Length>30</Length>
                <Width>5</Width>
                <Material>Copper</Material>
            </TopPart>
            <Handle>
                <Material type="Pine">Wood</Material>
            </Handle>
        </Visual>
        <Value>Non-collectible</Value>
    </Cutlery>
</FlatWare>
